### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wojciechbulaty** [akevinbailey/JmsStream#1]
Hi,

Thanks for sharing this codebase!

The license you have added to the project prevents us from using your source code you have submitted here. Would you be able to license it under Apache 2, MIT, or similar license, please?

Thanks!

"License Grant. The Software is the property of TIBCO Software Inc. ("TIBCO") or its licensors and is protectedby copyright and other laws. While TIBCO continues to own the Software, TIBCO hereby grants to Customer a limited, non-transferable, non-exclusive, royalty-free license to use the Software , _**in machine-readable, object code form**_ and solely for internal testing and development purposes, provided that in no event shall the Software be used for production purposes."

**Comment by akevinbailey** [comment]
Wojtek,

I wish I could release it under Apache 2.  TIBCO's lawyers wanted it to be very closed, so only TIBCO employees and customers could use it.  Since I now work for Software AG, I cannot touch this code anymore.

Sorry,

A. Kevin Bailey
